"""add subject, student_semester, subject_marks, marks_component tables

Revision ID: 97a2a7d2af43
Revises: ba5fe0c50734
Create Date: 2026-07-13 07:01:22.518721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a2a7d2af43'
down_revision: Union[str, Sequence[str], None] = 'ba5fe0c50734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_code')
    )
    op.create_table('student_semester',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('sgpa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_semester_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('grade_point', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_semester_id'], ['student_semester.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markscomponents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_marks_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('maximum_marks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['subject_marks_id'], ['subject_marks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markscomponents')
    op.drop_table('subject_marks')
    op.drop_table('student_semester')
    op.drop_table('subjects')
    # ### end Alembic commands ###
